Initial Refactors
CSEN-SCU/csen-174-f24-project-zenior pull request #22
Opened 2024-10-31 03:45 UTC by v3ceban

- Changed Nav dropdown to use shadcn/ui component
- Made Nav a server component, moved client logic into separate components
- Moved css files under @/styles
- Added super_admin to protected routes
- Changed protected routes redirects to "/", resolving infinite redirect to "/success/new-user"
  - This should be changed to "/login" when homepage gets a different purpose
- Added "/about" and "/privacy-policy" that are linked in footer
- Added user profile picture to session token
- Extracted user profile picture url from google into db
- Changed Nav logo to look like the one in Canva
- Changed footer copyright symbol to html-safe one
  - @marleyyvon do we even need it? we're under GPLv3.0, which is a copyleft license... pls review license terms and revise

2024-10-31 04:03 UTC, v3ceban commented
Also added predev npm isntall script to ensure you have all necessary dependencies when you start your dev server

2024-10-31 04:21 UTC, marleyyvon submitted a review, later dismissed
We can remove that, will update on the other branch shortly.

2024-10-31 21:53 UTC, miaadele submitted a review, later dismissed

2024-11-04 05:18 UTC, jcisneros1999 requested changes

2024-11-04 05:18 UTC, jcisneros1999 commented on src/components/Navbar/Navbar.jsx
> +import { Login, Logout } from "./AuthButtons";
Question: Should we make all paths use the @/ convention for consistency?

2024-11-04 05:19 UTC, jcisneros1999 commented on src/components/Navbar/Navbar.jsx
> +import { Login, Logout } from "./AuthButtons";
Also feel free to tell me to kick rocks if its not important lol. I got no strong opinion on this, consistency just helps make the project feel like it is cohesive.

2024-11-04 16:10 UTC, miaadele commented on src/components/Navbar/Navbar.jsx
> +import { Login, Logout } from "./AuthButtons";
Sure, I can change it

2024-11-04 17:25 UTC, vaniaggarwal approved these changes
looks good to me

2024-11-05 05:23 UTC, marleyyvon approved these changes

2024-11-05 19:17 UTC, miaadele approved these changes

2024-11-05 21:15 UTC, merged