Created Faculty Profile Page
CSEN-SCU/csen-174-f24-project-zenior pull request #24
Opened 2024-10-31 17:11 UTC by vaniaggarwal

- created the form and put it under faculty
- also created a page.jsx for the profile navigation 
- need to make Department portion a dropdown

2024-10-31 18:50 UTC, miaadele approved these changes
Looks good!

2024-10-31 22:15 UTC, v3ceban requested changes
Looks good.

For everyone FYI: Minor version updates of next, prisma, and other deps are appreciated. If it promts you for a major update - pls don't go with it untill discussed with group @marleyyvon @miaadele @jcisneros1999 @vaniaggarwal 

To do before merning for @vaniaggarwal :
- **src/components/FacultyAccountForm.jsx**: please uncomment and use component proptypes. Add any if missing (eslint should highlight these as errors)
- **src/app/(faculty)/profile/profile.module.css**: please move to other styles under **src/styles/**
- And while you at user profile forms, pls change default profile picture in faculty/student/my-team forms to **session.user.image**

2024-11-04 18:52 UTC, v3ceban approved these changes

2024-11-04 19:52 UTC, marleyyvon approved these changes

2024-11-04 20:17 UTC, merged