Created Confirmation Popups
CSEN-SCU/csen-174-f24-project-zenior pull request #38
Opened 2024-11-20 21:04 UTC by vaniaggarwal

- added confirmation popup when someone posts a project upon clicking post project on proposal form
- in studentoverview, added popups for reject and accept in group and team requests
- need to still do the request to join popup due to client-server side errors

2024-11-20 21:37 UTC, miaadele approved these changes

2024-11-20 21:48 UTC, v3ceban requested changes
StudentOverview errors out (see comments)

2024-11-20 21:48 UTC, v3ceban commented on src/components/StudentOverview.jsx
> +  const { toast } = useToast();
This is not passed down

2024-11-20 21:48 UTC, v3ceban commented on src/components/StudentOverview.jsx
> +    })
this is undefined because `toast` from `TeamrRequest` is not passed down

2024-11-20 21:48 UTC, v3ceban commented on src/components/StudentOverview.jsx
> +
same here, this errors out

2024-11-20 21:48 UTC, v3ceban commented on src/components/StudentOverview.jsx
> +const GroupRequest = ({ grouprequests, handleAcceptToast }) => {
Add `handleAcceptToast` to `GroupRequest.propTypes`

2024-11-20 21:48 UTC, v3ceban commented on src/components/StudentOverview.jsx
> +                      onClick={(e) => {
e unused

2024-11-20 21:48 UTC, v3ceban commented on src/components/ProjectProposalForm/Proposal.jsx
This is good

2024-12-02 02:13 UTC, v3ceban approved these changes
Good

2024-12-02 03:11 UTC, miaadele approved these changes

2024-12-02 03:11 UTC, merged